package com.example.movierental.mybatis.dao;

import com.example.movierental.mybatis.model.Genre;
import java.util.List;

public interface GenreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    int insert(Genre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    Genre selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    List<Genre> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.GENRE
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    int updateByPrimaryKey(Genre record);
}