package com.example.movierental.mybatis.dao;

import com.example.movierental.mybatis.model.MovieGenre;
import java.util.List;

public interface MovieGenreMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MOVIE_GENRE
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    int insert(MovieGenre record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table PUBLIC.MOVIE_GENRE
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    List<MovieGenre> selectAll();
}