package com.example.movierental.mybatis.model;

public class Movie {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.ID
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.DESCRIPTION
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.DIRECTOR
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    private String director;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.RELEASEDATE
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    private String releasedate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.NAME
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE.CUSTOMER_ID
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    private Long customerId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.ID
     *
     * @return the value of PUBLIC.MOVIE.ID
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.ID
     *
     * @param id the value for PUBLIC.MOVIE.ID
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.DESCRIPTION
     *
     * @return the value of PUBLIC.MOVIE.DESCRIPTION
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.DESCRIPTION
     *
     * @param description the value for PUBLIC.MOVIE.DESCRIPTION
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.DIRECTOR
     *
     * @return the value of PUBLIC.MOVIE.DIRECTOR
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    public String getDirector() {
        return director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.DIRECTOR
     *
     * @param director the value for PUBLIC.MOVIE.DIRECTOR
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    public void setDirector(String director) {
        this.director = director;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.RELEASEDATE
     *
     * @return the value of PUBLIC.MOVIE.RELEASEDATE
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    public String getReleasedate() {
        return releasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.RELEASEDATE
     *
     * @param releasedate the value for PUBLIC.MOVIE.RELEASEDATE
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    public void setReleasedate(String releasedate) {
        this.releasedate = releasedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.NAME
     *
     * @return the value of PUBLIC.MOVIE.NAME
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.NAME
     *
     * @param name the value for PUBLIC.MOVIE.NAME
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE.CUSTOMER_ID
     *
     * @return the value of PUBLIC.MOVIE.CUSTOMER_ID
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    public Long getCustomerId() {
        return customerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE.CUSTOMER_ID
     *
     * @param customerId the value for PUBLIC.MOVIE.CUSTOMER_ID
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    public void setCustomerId(Long customerId) {
        this.customerId = customerId;
    }
}