package com.example.movierental.mybatis.model;

public class MovieGenre {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE_GENRE.MOVIE_ID
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    private Long movieId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column PUBLIC.MOVIE_GENRE.GENRES_ID
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    private Long genresId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE_GENRE.MOVIE_ID
     *
     * @return the value of PUBLIC.MOVIE_GENRE.MOVIE_ID
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    public Long getMovieId() {
        return movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE_GENRE.MOVIE_ID
     *
     * @param movieId the value for PUBLIC.MOVIE_GENRE.MOVIE_ID
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    public void setMovieId(Long movieId) {
        this.movieId = movieId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column PUBLIC.MOVIE_GENRE.GENRES_ID
     *
     * @return the value of PUBLIC.MOVIE_GENRE.GENRES_ID
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    public Long getGenresId() {
        return genresId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column PUBLIC.MOVIE_GENRE.GENRES_ID
     *
     * @param genresId the value for PUBLIC.MOVIE_GENRE.GENRES_ID
     *
     * @mbg.generated Mon Apr 17 17:44:09 EEST 2023
     */
    public void setGenresId(Long genresId) {
        this.genresId = genresId;
    }
}